/* PROJECT PACE — the baseline, produced by the SAME parser that reads the weekly
 * uploads (lib/paceWorkbook). Generating it any other way let the baseline and an
 * upload disagree over details like an observer's name, which then surfaced as a
 * screenful of changes that never happened.
 * Pareto snapshot 14 Jul – 6 Aug 2026: 3,638 min lost across 398 stops on three measured lines.
 * Generated from Project_Pace_Action_Tracker.xlsx — edit there, re-extract here. */

export interface PaceLine { key: string; name: string; variant?: string; q1: number; q2: number; q3: number; q4: number; weekly: (number | null)[]; }
export interface ParetoRow { category: string; mins: number; events: number; minPerEvent: number; profile: string; l2: number; l7: number; l10: number; }
export interface PaceAction { ref: string; priority: number; line: string; category: string; problem?: string; action?: string; who?: string; owner?: string; due?: string; status: string; flag: string; }
export interface PaceObservation { observer: string; lens: string; text: string; }

/** Q1 starts August 2026; each quarter is 13 weeks. Weekly actuals run from W/C 3 Aug 2026. */
export const PACE_START = Date.UTC(2026, 7, 3);
export const PACE_PERIOD = "14 Jul – 6 Aug 2026";
/** The baseline upload every later week is measured against. */
export const PACE_BASELINE_AT = Date.UTC(2026, 7, 6);
export const PACE_TOTAL_MINS = 3638;
export const PACE_TOTAL_STOPS = 398;

export const PACE_LINES: PaceLine[] = [
  { key: "2A", name: "Line 2A", variant: "Line 2 \u2014 measured independently", q1: 44, q2: 50, q3: 52, q4: 55, weekly: [42, 41, 35, 47, 44, 46] },
  { key: "2B", name: "Line 2B", variant: "Line 2 \u2014 measured independently", q1: 44, q2: 50, q3: 52, q4: 55, weekly: [28, 30, 29, null, 28, 34] },
  { key: "7", name: "Line 7", variant: undefined, q1: 39, q2: 42, q3: 44, q4: 46, weekly: [37, 44, 37, 35, 35, 38] },
  { key: "10", name: "Line 10", variant: undefined, q1: 48, q2: 51, q3: 53, q4: 55, weekly: [56, 59, 52, 57, 54, 52] },
];

export const PACE_PARETO: ParetoRow[] = [
  { category: "Changeovers", mins: 984.5, events: 64, minPerEvent: 15.4, profile: "Long-stop", l2: 930, l7: 47.4, l10: 7.1 },
  { category: "General line organisation", mins: 604, events: 39, minPerEvent: 15.5, profile: "Long-stop", l2: 424, l7: 179, l10: 1 },
  { category: "Brillopack snags", mins: 297, events: 55, minPerEvent: 5.4, profile: "Frequency", l2: 297, l7: 0, l10: 0 },
  { category: "Stock starvation", mins: 288, events: 20, minPerEvent: 14.4, profile: "Long-stop", l2: 283, l7: 5, l10: 0 },
  { category: "engineering", mins: 281, events: 12, minPerEvent: 23.4, profile: "Long-stop", l2: 281, l7: 0, l10: 0 },
  { category: "Consumable changes", mins: 148, events: 38, minPerEvent: 3.9, profile: "Frequency", l2: 139, l7: 4.7, l10: 4.3 },
  { category: "Break management", mins: 132.7, events: 20, minPerEvent: 6.6, profile: "Frequency", l2: 105, l7: 11, l10: 16.7 },
  { category: "Quality", mins: 124.9, events: 20, minPerEvent: 6.2, profile: "Frequency", l2: 82, l7: 20.3, l10: 22.6 },
  { category: "Quality line stops", mins: 90, events: 6, minPerEvent: 15, profile: "Long-stop", l2: 90, l7: 0, l10: 0 },
  { category: "Late start", mins: 86, events: 4, minPerEvent: 21.5, profile: "Long-stop", l2: 86, l7: 0, l10: 0 },
  { category: "Robot / automation", mins: 61.3, events: 25, minPerEvent: 2.5, profile: "Frequency", l2: 0, l7: 0, l10: 61.3 },
  { category: "Line flow backup", mins: 59, events: 25, minPerEvent: 2.4, profile: "Frequency", l2: 59, l7: 0, l10: 0 },
  { category: "Packaging or equipment issues", mins: 59, events: 4, minPerEvent: 14.8, profile: "Long-stop", l2: 59, l7: 0, l10: 0 },
  { category: "Trial", mins: 53, events: 2, minPerEvent: 26.5, profile: "Long-stop", l2: 53, l7: 0, l10: 0 },
  { category: "Waiting for product", mins: 52, events: 2, minPerEvent: 26, profile: "Long-stop", l2: 52, l7: 0, l10: 0 },
  { category: "Team meeting", mins: 43, events: 4, minPerEvent: 10.8, profile: "Long-stop", l2: 43, l7: 0, l10: 0 },
  { category: "Line staff capability", mins: 40.7, events: 14, minPerEvent: 2.9, profile: "Mixed", l2: 26, l7: 11.4, l10: 3.3 },
  { category: "Business systems", mins: 40.2, events: 3, minPerEvent: 13.4, profile: "Long-stop", l2: 27, l7: 13.2, l10: 0 },
  { category: "GIC failure", mins: 37, events: 2, minPerEvent: 18.5, profile: "Long-stop", l2: 37, l7: 0, l10: 0 },
  { category: "Operator error", mins: 35.4, events: 8, minPerEvent: 4.4, profile: "Mixed", l2: 33, l7: 0.5, l10: 1.9 },
  { category: "Bagger printer", mins: 33, events: 5, minPerEvent: 6.6, profile: "Mixed", l2: 33, l7: 0, l10: 0 },
  { category: "Box compliance / box damage", mins: 23.5, events: 3, minPerEvent: 7.8, profile: "Mixed", l2: 23.5, l7: 0, l10: 0 },
  { category: "Set up", mins: 20.5, events: 5, minPerEvent: 4.1, profile: "Mixed", l2: 9, l7: 8.7, l10: 2.8 },
  { category: "Equipment", mins: 17.3, events: 4, minPerEvent: 4.3, profile: "Mixed", l2: 14, l7: 3.3, l10: 0 },
  { category: "Reject management", mins: 12.7, events: 7, minPerEvent: 1.8, profile: "Mixed", l2: 11.7, l7: 1, l10: 0 },
  { category: "Checkweigher", mins: 8.3, events: 5, minPerEvent: 1.7, profile: "Mixed", l2: 0, l7: 8.3, l10: 0 },
  { category: "Electrical issue", mins: 4.1, events: 1, minPerEvent: 4.1, profile: "Mixed", l2: 0, l7: 0, l10: 4.1 },
  { category: "Tipper", mins: 2.1, events: 1, minPerEvent: 2.1, profile: "Mixed", l2: 0, l7: 0, l10: 2.1 },
];

export const PACE_ACTIONS: PaceAction[] = [
  { ref: "T-001", priority: 1, line: "Line 2", category: "Changeovers", problem: "SKU changeovers taking too long \u2014 14 stops, 80 mins lost total.", action: "Training the operator how to make best use of time, WIP -N.b created a accountable SOP. Working with Dan Wilde to get it ready for training launch.", who: "Production", owner: "Ronnie (CI)", due: "2026-08-31", status: "In progress", flag: "OVERDUE" },
  { ref: "T-002", priority: 1, line: "Line 2", category: "Changeovers", problem: "Team need direct supervison and coaching on the new Changeover SOP;s,", action: "Team require support , training on best practice , sit with the teams get all team memebers up to the acceptable loss time standard Repeat as above under the same training.", who: "Production", owner: "Ronnie (CI)", due: "2026-08-31", status: "In progress", flag: "OVERDUE" },
  { ref: "T-003", priority: 1, line: "All lines", category: "Changeovers", problem: "No set standard agency manning on any shift", action: "Each shift is to find set people for 2,7,10 lock them in as a standard manning and  work with the agency team on site to deliver that standard manning. B & C shift have core manning set up for line 2, A shift are 50%, waiting for RedRock support. Rotating core manning to be trialed on B shift to increase the skill set of the team. Target is 15 names per shift", who: "Production", owner: "Alex Hamilton", due: "2026-08-03", status: "Done", flag: "Done" },
  { ref: "T-004", priority: 1, line: "Line 2", category: "Changeovers", problem: "Redundent film taking up space in the area", action: "Remove the redundant / slow moving films from the holder, replace with full high moving films, Redundant film has been removed, also part reel have been removed. a process will be put together to add back the part films while not impacting the line performance, The 2 film holders are being assigned to keep new and old film from getting mixed up.", who: "Production", owner: "Alex Hamilton", due: "2026-08-28", status: "In progress", flag: "OVERDUE" },
  { ref: "T-011", priority: 1, line: "Line 2", category: "Changeovers", problem: "Qa team  - opportunity for them to take specific activities during changeovers", action: "brief the team  -  get feed back  -", who: "Technical", owner: "Steve Wright (Technical)", due: "2026-08-10", status: "Done", flag: "Done" },
  { ref: "T-006", priority: 1, line: "Line 2", category: "Changeovers", problem: "Multiple \"same product, different batch\" during the same order", action: "New technical process to reduce paperwork = time ,  on change overs.  Testing to be carried out in IFS to replicate the proposal of multiple PL codes onto the same production order.  Review other opportunities for QA's to add value on the line,", who: "Technical", owner: "Steve Wright (Technical)", due: "2026-08-28", status: "Open", flag: "OVERDUE" },
  { ref: "T-007", priority: 1, line: "Line 2", category: "Changeovers", problem: "MU A4 side labels", action: "look for a way to make this role less time consuming, remove the label application from this process and print the document in the SI room,", who: "Technical", owner: "Steve Wright (Technical)", due: "2026-09-14", status: "Done", flag: "Done" },
  { ref: "T-008", priority: 1, line: "Line 2", category: "Changeovers", problem: "Communication and awareness of material quality leading to delays and additional changeovers", action: "2x New Mobile phone -or- Tablet device to be ordered - One for Celox & One for All Production Lines - Dedicated QA Operator.  Tablets are the preferred option using MS Teams as a communication tool.  Question over access to Celox camera feeds for Celox QA Ops to get live feedback on the line.", who: "Technical", owner: "Steve Wright (Technical)", due: "2026-08-28", status: "Open", flag: "OVERDUE" },
  { ref: "T-009", priority: 1, line: "All lines", category: "Changeovers", problem: "The machine ops feedback is that none of the staff listen or know they are running the line.", action: "New Red high vis vests to be ordered for all operational leadership, machine ops, SM and SPM. this will show a clear connection between management and the machine ops. - These are being ordered 19/08/2026.", who: "Production", owner: "Alex Hamilton", due: "2026-08-31", status: "In progress", flag: "OVERDUE" },
  { ref: "T-010", priority: 2, line: "Line 2", category: "General line organisation", problem: "2nd highest frequency of stop, the detail states line stopping because of pallet changes line a", action: "buy a belt to add lengh to the exisitng line, this will act as a time buffer, in principle will eliminate short stopages and help with pallet change overs on the end of the line", who: "Production", owner: "Rob Scott (Shift A)", due: "2026-08-21", status: "In progress", flag: "OVERDUE" },
  { ref: "T-011", priority: 2, line: "Line 2", category: "General line organisation", problem: "line op, has to do a lot of paperwork on changeovers and during runs opportunuity to remove none value activities", action: "Work with Steve to try and remove elements that the QC could do and not the line op example sign of the bas every 15 min\u201d Labels - work with Steve - remove the process of the team sticking labels to an A4 piece of paper , \u201c just print the A4 piece of paper\u201d", who: "Production", owner: "Paul Armitage (Shift B)", due: "2026-08-21", status: "In progress", flag: "OVERDUE" },
  { ref: "T-012", priority: 3, line: "Line 2", category: "Brillopack snags", problem: "Brillopak crate starvation and tray-lift faults \u2014 14 stops, 72 mins lost total.", action: "Root cause found with Brillopak, Sensor adjusted and the issue is not presenting at all now.", who: "CI", owner: "Ronnie (CI)", due: "2026-07-30", status: "Done", flag: "Done" },
  { ref: "T-013", priority: 3, line: "Line 2", category: "Brillopack snags", problem: "We cant see the granular details of the 2b Brollopack snags all data form categories only", action: "Build an adoc Pareto that automatically pulls the brillopack problems into a specific pareto", who: "Production", owner: "Rowland (Ops Lead)", due: "2026-08-03", status: "Done", flag: "Done" },
  { ref: "T-014", priority: 3, line: "Line 2", category: "Brillopack snags", problem: "More understanding of the robot problems is required 3/8/26 Jarik was instructed that on the 4/8/26 concentrate on line 2b , Rowland and Chris to spend time on the line", action: "Pareto ready, agreed focus on 2b Chris and Rowland", who: "Production", owner: "Rowland (Ops Lead)", due: "2026-08-07", status: "Done", flag: "Done" },
  { ref: "T-015", priority: 3, line: "Line 2", category: "Brillopack snags", problem: "Baskets get caught in the machine, the operator does not have a tool to pull out the basket, they have to call Technicans or break saftey procedure to get to the basket", action: "ordered 4, 1 L2, 1 for sp1, and 2 spare", who: "Production", owner: "Rowland (Ops Lead)", due: "2026-08-07", status: "Done", flag: "Done" },
  { ref: "T-016", priority: 3, line: "Line 2", category: "Brillopack snags", problem: "Bag drops are skewing on landing due to side guards and design of kickplate", action: "Kick plate needs to flip bags to be the correct orientation on the robot. Kick plate adjusted and height of kickplate adjusted. Ops running without this activated which makes it worse. Around 1 in 12 bags skewed slightly beyond 22.5\u00b0 tolerance.", who: "Engineering", owner: "Chris Smyth (Engineering)", due: "2026-08-18", status: "Done", flag: "Done" },
  { ref: "T-017", priority: 3, line: "Line 2", category: "Brillopack snags", problem: "Bag transfer to Newtec CW skewing presentation to BP.", action: "Trial raising incline conveyor and speed up to allow better presentation and flattening of bag. Centralising guards moved out of the way as causing more issues than solving. Incline elevator speed increased to prevent checkweigher from skewing packs on transfer. Quality of infeed greatly improved. Around 1 in 20 bags skewed slightly beyond 22.5\u00b0 tolerance.", who: "Engineering", owner: "Chris Smyth (Engineering)", due: "2026-08-20", status: "Done", flag: "Done" },
  { ref: "T-018", priority: 3, line: "Line 2", category: "Brillopack snags", problem: "Filling trays is pushed to the max on tuning whilst trying to achieve 75ppm. This is due to turning the packs.", action: "Trial run with the aid of Sam, working with Brillopak to revisit putting bags into the trays, long edge forward and vibrate them to try and achieve a better presentation when stacking.\nBrillopak have now adjusted the packing format so that 2 packs are turned and the rest are long edge forward. The trays are acceptable and stack well without damage to potatoes or \"balancing\" of boxes. Achieving 75ppm but still getting approx 2 bags unpicked every 1-2 minutes. More fine tuning to do by BrilloPak following installation of BDU filler system last week.\nREQUIRES FURTHER TUNING AFTER BDU INSTALL", who: "Engineering", owner: "Chris Smyth (Engineering)", due: "2026-08-26", status: "Done", flag: "Done" },
  { ref: "T-010", priority: 4, line: "Line 2", category: "Stock starvation", problem: "Reports of FLT drivers not keeping the production line full", action: "will investigate further, find out what is really happening , speak to rowland has some insight from Kasper. There is no issue with the loading of the line from a FLT point. The only issue that may arise going forward is when the line achieves the 75 ppm, but currently there is little to suggest that this is an issue ATM", who: "Production", owner: "Paul Selby", due: "2026-08-14", status: "Done", flag: "" },
  { ref: "T-020", priority: 4, line: "Line 2", category: "Stock starvation", problem: "Oculus infeed belt tripping out intermitently", action: "Engineering to resolve issue. Issue resolved by engineering", who: "Engineering", owner: "Chris Smyth (Engineering)", due: "2026-08-06", status: "Done", flag: "Done" },
  { ref: "T-021", priority: 4, line: "Line 2", category: "Stock starvation", problem: "Box tipper light curtain tripping", action: "Engineering to investigate and resolve. Issue resolved at the time but requires monitoring going forward", who: "Engineering", owner: "Chris Smyth (Engineering)", due: "2026-08-04", status: "Done", flag: "Done" },
  { ref: "T-022", priority: 4, line: "Line 2", category: "Stock starvation", problem: "Newtec not producing finished product due to film c/overs, product c/overs", action: "Procedure issue with the running of the line. Procedure requires improvement and planning on the film changes & product changes. This is handed over to production", who: "Production", owner: "Rob Scott (Shift A)", due: "2026-08-28", status: "In progress", flag: "OVERDUE" },
  { ref: "T-023", priority: 4, line: "Line 2", category: "Stock starvation", problem: "Quality of FLT drivers loading the box tippers varies causing challenges with getting the product to the line", action: "Use experienced FLT drivers until other drivers are up to the standard. Named drivers to load L2. Producton managers briefed and list of experienced FLT drivers created by the production managers", who: "Production", owner: "Paul Selby", due: "2026-08-07", status: "Done", flag: "Done" },
  { ref: "T-024", priority: 4, line: "Line 2", category: "Stock starvation", problem: "Ungraded stock coming to the line causing slow running", action: "Investigate and find out why this is happening and put a resolution in place. Lack of following procedure. Briefed line managers to ensure that this does not happen going forward and all incidents are investigated", who: "Production", owner: "Paul Selby", due: "2026-09-04", status: "Done", flag: "Done" },
  { ref: "T-025", priority: 5, line: "Line 2", category: "engineering", problem: "Occasional trips occuring on EFH panel due to linkage devices used instead of hard wired. These are reversing links.", action: "Source spare parts in case we have further issues.\nSpares are now on stock", who: "Engineering", owner: "Chris Smyth (Engineering)", due: "2026-08-14", status: "Done", flag: "Done" },
  { ref: "T-026", priority: 5, line: "Line 2", category: "engineering", problem: "Occasional trips occuring on EFH panel due to linkage devices used instead of hard wired. These are reversing links.", action: "Look for a permanent fix, hard wire contactors to eliminate issues with clip in devices", who: "Engineering", owner: "Chris Smyth (Engineering)", due: "2026-11-27", status: "Open", flag: "On track" },
  { ref: "T-027", priority: 7, line: "Line 2", category: "Break management", problem: "Team late back from breaks", action: "Man management , ensure all teams are told to be back on time no exceptions. A shift team brief completed at the tier 1 meeting 12:00 - 04.08.26. B shift will be briefed 05.08.2026 at the tier 1 - 08:30.", who: "Production", owner: "Alex Hamilton", due: "2026-08-06", status: "Done", flag: "Done" },
  { ref: "T-028", priority: 7, line: "All lines", category: "Break management", problem: "Breaks running over \u2014 4 stops, 17 mins lost total.", action: "Man management , ensure all teams are told to be back on time no exceptions, same as line 2, A & B shift - all section manager and machine ops have been informed during the tier 1 metings about break times.", who: "Production", owner: "Alex Hamilton", due: "2026-08-11", status: "Done", flag: "Done" },
  { ref: "T-029", priority: 11, line: "Line 2", category: "Robot / automation", problem: "Knowledge is held by one individual , restricting the ability to improve the line 2 b robot", action: "OEM on site 3 days of emersive training specifically on the robot technical settings\nSam Burrows spent 2 days with OEM engineer, we were adjustings settings in the program trying to fine tune, and we also went through some training to understand everything about the machine and how it works, we adjusted the test program ahead of the 1 hour trial carried out on OEM engineers last day on site.", who: "Engineering", owner: "Sam Burrows (Eng)", due: "2026-08-21", status: "Done", flag: "Done" },
  { ref: "T-030", priority: 11, line: "Line 10", category: "Robot / automation", problem: "Robot short stops \u2014 23 stops, 55 mins lost total (44% of the line).", action: "\"Wrist\" ordered and awaiting delivery. Will fit when arrives. Not yet delivered. Awaiting delivery from Abar.", who: "Engineering", owner: "Chris Smyth (Engineering)", due: "2026-09-04", status: "In progress", flag: "Due soon" },
  { ref: "T-031", priority: 11, line: "Line 10", category: "Robot / automation", problem: "Too many packs are going through the kicker belts and being rejected by the robot.", action: "Investigate cause and create action to rectify. \n45 minute video taken of the kicker belts running, during this time we lost 15 packs and this video needs to be analysed to look for the cause.", who: "Engineering", owner: "Sam Burrows (Eng)", due: "2026-09-11", status: "In progress", flag: "On track" },
  { ref: "T-032", priority: 13, line: "Line 2", category: "Packaging or equipment issues", problem: "clear indicator that the new film \" less holes\" runs significently better", action: "Lisa Perry, Majic", who: "Production", owner: "Rowland (Ops Lead)", due: "2026-10-31", status: "In progress", flag: "On track" },
  { ref: "T-033", priority: 3, line: "Line 2", category: "Brillopack snags", problem: "MU  installation, commisioning", action: "03/09/2026  Rowland and Chris to line study with Brilopack  expectation target 75ppm at a 98% effececny rate", who: "Engineering", owner: "Chris Smyth (Engineering)", due: "2026-09-03", status: "In progress", flag: "Due soon" },
  { ref: "T-034", priority: 3, line: "Line 2", category: "Stock starvation", problem: "Celox grading missed opotunity due to grading req on line because of potatoes that are not correctly size graded, particulalry those gathered from lane 8&9", action: "Gather sample data from Celox (A) to quantify amount of overflow in to lane A8 & A9 of over sized potatoes to allow next step of identify current understanding of working principle and standard settings for flow through Celox camera, along with analysing what trial tells us", who: "Production", owner: "Dan Wilde", due: "2026-09-11", status: "In progress", flag: "On track" },
  { ref: "T-035", priority: 3, line: "Line 2", category: "General line organisation", problem: "There is a disconnect between data discussed in Tier 1 & 2 meetings and actual state of performance with a view beyond anything other than the static data point in time", action: "Introduce a trial to add trended data, starting with line 2 and the appropriate horizon for Tier 1 & 2 meetings to see the live development of performance before further developing in to other metrics such as quality categories and upstream stock position", who: "Production", owner: "Dan Wilde", due: "2026-09-11", status: "In progress", flag: "On track" },
  { ref: "T-036", priority: 3, line: "Line 2", category: "Stock starvation", problem: "Unusure if we can feed at the required rate", action: "Investigate flow rate.. Reports we need 18 ton per hr\u2026 with a 20% expectecd rejection rate", who: "Production", owner: "Paul Selby", due: "2026-09-09", status: "In progress", flag: "Due soon" },
  { ref: "T-037", priority: 3, line: "All lines", category: "General line organisation", problem: "foucs drifs section managers currently don\u2019t spend the required amount of time to actually drive localised support to the lines.", action: "discuss with the section managers , splitting the factory floor \u2026 this related to unfderstanding speed control on baskets and Mus", who: "Production", owner: "Rowland (Ops Lead)", due: "2026-09-08", status: "In progress", flag: "Due soon" },
  { ref: "T-038", priority: 3, line: "Line 2", category: "Brillopack snags", problem: "Basket destaker  jams jamming on infeed white conveyour belt and actual de-staker \u2026", action: "flag to chris.. A sensor bracket needs desigining  to stop the basket white conveyor jams\u2026 get ot ordered through brillopack and enginerring", who: "Engineering", owner: "Rowland (Ops Lead)", due: "2026-09-08", status: "In progress", flag: "Due soon" },
  { ref: "T-039", priority: 3, line: "Line 2", category: "Brillopack snags", problem: "operator has to use foot pedal to move the baskets along into the destaker..  If not done in time the robot stops and causes a restart situation.. Min lost in a high frequecny", action: "can we automate ?  Is it on anyones plan to automate", who: "Engineering", owner: "Rowland (Ops Lead)", due: "2026-09-08", status: "In progress", flag: "Due soon" },
  { ref: "T-040", priority: 3, line: "Line 2", category: "General line organisation", problem: "currenlty no clear manning plan of where the people will go when we have a full atuomation on both liens, we have  10 people in buget , need to understand where the popel will og, and possibley potential bottlenecks once the plan is understood", action: "Rowland speak to Tanya , and do the packing  calculations \" how fast does the packer had to be to keep up with a 75ppm \" is it practical \" ?   8 seconds per basket 1 pallet every 5 min", who: "Production", owner: "Rowland (Ops Lead)", due: "2026-09-10", status: "In progress", flag: "Due soon" },
];

export const PACE_OBSERVATIONS: PaceObservation[] = [
  { observer: "Rowland", lens: "People", text: "Line leadership -  poor comunications - the line is silent from the opertator who is leading the line ?  Do they know they also lead the people ? B shift Polonia?  Very vocal full of energy is she the new line 2 operator , however she does run line 7" },
  { observer: "Rowland", lens: "People", text: "Standard manning  - Alex trying to get it imbedded facing resistance from production - not from the agency  ?" },
  { observer: "Rowland", lens: "People", text: "observed b shift skill  matrix, looks thin, even when ronnie said they had trainied multiple people ?" },
  { observer: "Rowland", lens: "Plant", text: "Speed test find the sweet spot need doing" },
  { observer: "Rowland", lens: "Plant", text: "Extend the belt  - L2A should resolve the frequent stops caused by  change of pallet and could result in having more space to do the new packimng technique" },
  { observer: "Rowland", lens: "Plant", text: "Basket decanting  issue, jamming on infeed white conveyour belt and actual de-staker \u2026 flag to chris.. A sensore bracket needs desigining  to stop the basket white conveyor james" },
  { observer: "Rowland", lens: "Process", text: "Label application onto an A4 sheet \" why not print just on A4\" ?" },
  { observer: "Rowland", lens: "Material", text: "Film \" holes\" major issue.. Lisa looking at it" },
  { observer: "Pauls", lens: "People", text: "FLT not causing downtime" },
  { observer: "Pauls", lens: "People", text: "Quality of the FLT driver does impact the process. Initially key experienced drivers should be on this line with the lesser experienced drivers training on the other lines. Line has not ran out but it gets tighter at times with inexperienced drivers" },
  { observer: "Pauls", lens: "Plant", text: "Box tipper light curtain causing stoppages. Line not affected" },
  { observer: "Pauls", lens: "Plant", text: "Oculus infeed belt trips out from time to time. This does affect the throughput but seems to have been resolved for the time being" },
  { observer: "Pauls", lens: "Process", text: "Product c/overs causing mixed product. Poor controls on c/over process. Often run one side of the Newtec with a different variety on the c/overs" },
  { observer: "Pauls", lens: "Process", text: "Ungraded product (1 box). Issue with grading - (See material comments)" },
  { observer: "Pauls", lens: "Material", text: "Occassionally ungraded product (Not been over the Celox) arrives to the line causing grading issues and slowing the process down. (Three boxes in total seen)" },
  { observer: "Pauls", lens: "Material", text: "Varying quality issues with the RM sometimes causes d/time at changeovers but not when the line is running and the varifill hoppers are full. Chasing Celox on grading quality" },
];
